### ISSUE TITLE
Mac:Safariでタイトルが表示されない

### ISSUE THREAD

**Issue by uribo** [yutannihilation/ggplot2-gyakubiki#2]
素敵なサイトを作ってくださりありがとうございます。私は普段Safariを使っているのですが、Safariだとタイトルが表示されないようです。

こんな感じになっています。

<img width="400" alt="ggplot2" src="https://cloud.githubusercontent.com/assets/228649/9446821/b7cacc42-4ace-11e5-9e21-58d6a5ae919b.png">

ソースを見ても、Chromeで出力されているタイトルが消えています...

``` html
<div class="mdl-card__title color15">
  <a href="http://qiita.com/berobero11/items/169d63071a54d7f64d0a" target="_blank"></a>
</div>
```

**Comment by yutannihilation** [comment]
報告ありがとうございます。むむ。。

**Comment by yutannihilation** [comment]
この部分があやしいのかも。

https://github.com/yutannihilation/ggplot2-gyakubiki/blob/b80a4120ac63cb98a2273cccc10ac626adb2f395/cards.js#L11

**Comment by yutannihilation** [comment]
textContentが標準らしいので修正してみました。

Node.textContent - Web API インターフェイス | MDN https://developer.mozilla.org/ja/docs/Web/API/Node/textContent

**Comment by uribo** [comment]
修正されているのを確認しました！nice work :+1:

**Comment by yutannihilation** [comment]
確認あざっした！
